{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Construindo árvore fixa...\n"
     ]
    },
    {
     "ename": "NameError",
     "evalue": "name 'Digraph' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[5]\u001b[39m\u001b[32m, line 75\u001b[39m\n\u001b[32m     73\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33m\"\u001b[39m\u001b[33mConstruindo árvore fixa...\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m     74\u001b[39m fixed_tree = build_fixed_tree()\n\u001b[32m---> \u001b[39m\u001b[32m75\u001b[39m \u001b[43mdraw_tree\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfixed_tree\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mtree_fixa\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m     77\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33m\"\u001b[39m\u001b[33mConstruindo árvore randômica...\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m     78\u001b[39m expr_random = generate_random_expression()\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[5]\u001b[39m\u001b[32m, line 8\u001b[39m, in \u001b[36mdraw_tree\u001b[39m\u001b[34m(node, filename)\u001b[39m\n\u001b[32m      7\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mdraw_tree\u001b[39m(node, filename=\u001b[33m\"\u001b[39m\u001b[33mtree\u001b[39m\u001b[33m\"\u001b[39m):\n\u001b[32m----> \u001b[39m\u001b[32m8\u001b[39m     dot = \u001b[43mDigraph\u001b[49m(comment=\u001b[33m\"\u001b[39m\u001b[33mÁrvore de Expressão\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m     10\u001b[39m     \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34madd_nodes_edges\u001b[39m(node, parent=\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[32m     11\u001b[39m         \u001b[38;5;28;01mif\u001b[39;00m node \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[31mNameError\u001b[39m: name 'Digraph' is not defined"
     ]
    }
   ],
   "source": [
    "class Node:\n",
    "    def __init__(self, value):\n",
    "        self.value = value\n",
    "        self.left = None\n",
    "        self.right = None\n",
    "\n",
    "class BinarySearchTree:\n",
    "    def __init__(self):\n",
    "        self.root = None\n",
    "\n",
    "    def insert(self, value):\n",
    "        if self.root is None:\n",
    "            self.root = Node(value)\n",
    "        else:\n",
    "            self._insert(self.root, value)\n",
    "\n",
    "    def _insert(self, current, value):\n",
    "        if value < current.value:\n",
    "            if current.left is None:\n",
    "                current.left = Node(value)\n",
    "            else:\n",
    "                self._insert(current.left, value)\n",
    "        else:\n",
    "            if current.right is None:\n",
    "                current.right = Node(value)\n",
    "            else:\n",
    "                self._insert(current.right, value)\n",
    "\n",
    "    def search(self, value):\n",
    "        return self._search(self.root, value)\n",
    "\n",
    "    def _search(self, current, value):\n",
    "        if current is None:\n",
    "            return False\n",
    "        if current.value == value:\n",
    "            return True\n",
    "        elif value < current.value:\n",
    "            return self._search(current.left, value)\n",
    "        else:\n",
    "            return self._search(current.right, value)\n",
    "\n",
    "    def delete(self, value):\n",
    "        self.root = self._delete(self.root, value)\n",
    "\n",
    "    def _delete(self, current, value):\n",
    "        if current is None:\n",
    "            return current\n",
    "\n",
    "        if value < current.value:\n",
    "            current.left = self._delete(current.left, value)\n",
    "        elif value > current.value:\n",
    "            current.right = self._delete(current.right, value)\n",
    "        else:\n",
    "            if current.left is None and current.right is None:\n",
    "                return None\n",
    "            elif current.left is None:\n",
    "                return current.right\n",
    "            elif current.right is None:\n",
    "                return current.left\n",
    "            else:\n",
    "                successor = self._min_value_node(current.right)\n",
    "                current.value = successor.value\n",
    "                current.right = self._delete(current.right, successor.value)\n",
    "\n",
    "        return current\n",
    "\n",
    "    def _min_value_node(self, node):\n",
    "        current = node\n",
    "        while current.left is not None:\n",
    "            current = current.left\n",
    "        return current\n",
    "\n",
    "    def height(self):\n",
    "        return self._height(self.root)\n",
    "\n",
    "    def _height(self, node):\n",
    "        if node is None:\n",
    "            return -1\n",
    "        return 1 + max(self._height(node.left), self._height(node.right))\n",
    "\n",
    "    def depth(self, value):\n",
    "        return self._depth(self.root, value, 0)\n",
    "\n",
    "    def _depth(self, current, value, level):\n",
    "        if current is None:\n",
    "            return -1\n",
    "        if current.value == value:\n",
    "            return level\n",
    "        elif value < current.value:\n",
    "            return self._depth(current.left, value, level + 1)\n",
    "        else:\n",
    "            return self._depth(current.right, value, level + 1)\n",
    "\n",
    "    def visualize(self, filename=\"bst\"):\n",
    "        dot = Digraph(comment=\"Árvore Binária de Busca\")\n",
    "\n",
    "        def add_nodes_edges(node):\n",
    "            if node is None:\n",
    "                return\n",
    "            dot.node(str(id(node)), str(node.value))\n",
    "            if node.left:\n",
    "                dot.edge(str(id(node)), str(id(node.left)))\n",
    "                add_nodes_edges(node.left)\n",
    "            if node.right:\n",
    "                dot.edge(str(id(node)), str(id(node.right)))\n",
    "                add_nodes_edges(node.right)\n",
    "\n",
    "        add_nodes_edges(self.root)\n",
    "        dot.render(filename, format=\"png\", cleanup=True)\n",
    "        print(f\"Árvore gerada: {filename}.png\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"\\n=== Árvore Fixa ===\")\n",
    "    bst_fixed = BinarySearchTree()\n",
    "    valores_fixos = [55, 30, 80, 20, 45, 70, 90]\n",
    "    for v in valores_fixos:\n",
    "        bst_fixed.insert(v)\n",
    "\n",
    "    bst_fixed.visualize(\"bst_fixa\")\n",
    "\n",
    "    print(\"Busca pelo 45:\", bst_fixed.search(45))\n",
    "    print(\"Altura da árvore:\", bst_fixed.height())\n",
    "    print(\"Profundidade do nó 45:\", bst_fixed.depth(45))\n",
    "\n",
    "    print(\"Removendo 30...\")\n",
    "    bst_fixed.delete(30)\n",
    "    bst_fixed.visualize(\"bst_fixa_removido\")\n",
    "\n",
    "    print(\"Inserindo 60...\")\n",
    "    bst_fixed.insert(60)\n",
    "    bst_fixed.visualize(\"bst_fixa_inserido\")\n",
    "\n",
    "    print(\"\\n=== Árvore Randômica ===\")\n",
    "    bst_random = BinarySearchTree()\n",
    "    valores_random = random.sample(range(1, 200), 15)\n",
    "    print(\"Valores randômicos:\", valores_random)\n",
    "\n",
    "    for v in valores_random:\n",
    "        bst_random.insert(v)\n",
    "\n",
    "    bst_random.visualize(\"bst_randomica\")\n",
    "    print(\"Altura da árvore randômica:\", bst_random.height())"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.11.4 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "5238573367df39f7286bb46f9ff5f08f63a01a80960060ce41e3c79b190280fa"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
